### ISSUE TITLE
Check State of Formula Serialization

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#7] opened 2015-12-07 16:21 UTC
`FormulaManager` has methods `dumpFormula` and `parse` for formula serialization, and there are some tests in `SolverFormulaIOTest`. We should look at this and check whether it works in all cases.

**Comment by cheshire** [comment] 2016-01-11 12:31
- Why we don't allow serialization of `Formula` instances? It's a very valid use case.
 - For Z3, why we don't just use `ast_to_string`?

**Comment by PhilippWendler** [comment] 2016-01-12 08:25
> Why we don't allow serialization of Formula instances? It's a very valid use case.

We can do this, sure, though I suggest this would be an additional feature and ticket (and there are some problems, such as needing a context for deserialization which does not fit nicely with Java's deserialization API).

> For Z3, why we don't just use ast_to_string?

I do not know what format this outputs, but for the output format of `dumpFormula`, there are several requirements:
- It needs to automatically introduce abbreviations for common sub terms (`let` or `define-fun`) in order to avoid exponential explosion.
- It needs to produce a format that is readable by `parse` with all solvers, which in particular means that it declares all used functions and that it asserts the exported formula.

**Comment by cheshire** [comment] 2016-01-25 18:04
Translation works for all combinations of solvers, except for Princess.
Trying to put a formula into Princess dies with "java.lang.NoClassDefFoundError: smtlib/parser".
@stieglma Do we have a missing import?
Formulas serialized by Princess can not be read by any other solver (ironically, including Princess) due to the `(reset)` command Princess adds in the beginning.

**Comment by stieglma** [comment] 2016-01-25 18:21
The reset command can just be removed, it is added manually by us in ```line 267``` in ```PrincessEnvironment```.
``` out.append("(reset)\n(set-logic AUFLIA)\n");```
I don't understand why dumping and parsing shouldn't work with Princess. There are even unit-tests covering that in the class ```SolverFormulaIOTest```, and they are working just fine, otherwise Travis would complain about it.

**Comment by cheshire** [comment] 2016-01-25 18:25
SolverFormulaIOTest definitely doesn't do what the test I have just
committed does: testing every combination of solvers for dumping/parsing.

Maybe the incorrect dependencies are due to the fact that I was running
tests from IDE.
Formulas dumped by Princess definitely can't be read by any other solver,
SolverFormulaIOTest doesn't even check whether they can be read by Princess.

**Comment by stieglma** [comment] 2016-01-25 18:29
Oh, I think this should then be added there. I was heavily relying on these tests while implementing parsing and dumping for Princess.

**Comment by cheshire** [comment] 2016-01-25 18:31
I've confirmed that dumping from Princess worked, IntelliJ dependencies
were missconfigured.
However I think we should check dumping and parsing for all possible
combinations, cf TranslateFormulaTest.

**Comment by cheshire** [comment] 2016-01-25 19:30
OK after removing `(reset)` parsing and dumping seems to work!

**Closed by cheshire** 2016-01-25 19:30 UTC
