### ISSUE TITLE
SMTInterpol throws SMTLibException

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-smt#107] opened 2017-03-09 12:21 UTC
Currently, all checks which go through SMTInterpol and result in an UNKNOWN status, get converted to a runtime exception `SMTLibException`. This is inconsistent with other solvers, which instead go for a checked `SolverException`.

**Comment by cheshire** [comment] 2017-03-09 14:00
I can trivially fix this, but I'm a bit confused why it was done this way in the first place, the `SMTLibException` is even explicitly created.

**Comment by PhilippWendler** [comment] 2017-04-02 13:37
All solvers should throw unchecked exceptions, except in cases where we know that something is not a bug but an expected failure of the solver. The goal is to distinguish clearly between expected failures and bugs, in order to not hide the latter. Bugs should produce unchecked exceptions such that they get noticed, reported, and fixed. For this reason we use whitelists of expected failures to be converted into `SolverException`s. This is implemented in the same way for all four solvers.

**Comment by cheshire** [comment] 2017-04-05 10:42
@PhilippWendler right OK, what about "unknown" verdicts? In SMTInterpol, we throw `SMTLibException` in many cases.
Yet unknown verdicts are not always unexpected (e.g. integer non-linear arithmetic, etc).

Should they also throw unchecked exceptions? I don't think that's what Z3 does.

**Comment by PhilippWendler** [comment] 2017-04-05 11:14
Exactly, expected unknowns for non-linear arithmetic should throw `SolverException`. However, SMTInterpol does not have such logics.

**Comment by cheshire** [comment] 2017-04-05 11:16
It returns a `ReasonUnknown` enum, which has an option `INCOMPLETE` which seems to be exactly what a checked exception is for (decision procedure is incomplete).

Also I think in a switch statement it would be better to go explicitly through all options.

**Comment by PhilippWendler** [comment] 2017-04-05 15:01
It has `ReasonUnknown.INCOMPLETE`, but this value should never occur currently except for a bug in SMTInterpol.

**Comment by kfriedberger** [comment] 2017-12-22 22:04
Closing issue as "won't be fixed".

**Closed by kfriedberger** 2017-12-22 22:04 UTC
Labels: SMTInterpol
