### ISSUE TITLE
Exception when Z3 is interrupted during push()

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#291] opened 2023-01-16 07:14 UTC
With JavaSMT 3.14.3-7-ge7d54ab2 we see the following exception in CPAchecker:
```
Exception in thread "main" com.microsoft.z3.Z3Exception: push canceled
	at com.microsoft.z3.Native.solverPush(Native.java:4892)
	at org.sosy_lab.java_smt.solvers.z3.Z3AbstractProver.push(Z3AbstractProver.java:205)
	at org.sosy_lab.java_smt.api.BasicProverEnvironment.push(BasicProverEnvironment.java:36)
	at org.sosy_lab.cpachecker.util.predicates.smt.BasicProverEnvironmentView.push(BasicProverEnvironmentView.java:36)
	at org.sosy_lab.cpachecker.util.predicates.smt.Solver.isUnsatUncached(Solver.java:508)
	at org.sosy_lab.cpachecker.util.predicates.smt.Solver.isUnsat(Solver.java:397)
	at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.modelToPolicyBound(PolicyIterationManager.java:1124)
	at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.getPolicyBound(PolicyIterationManager.java:755)
	at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.performAbstraction(PolicyIterationManager.java:897)
	at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyIterationManager.strengthen(PolicyIterationManager.java:406)
	at org.sosy_lab.cpachecker.cpa.policyiteration.PolicyCPA.strengthen(PolicyCPA.java:242)
	at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.callStrengthen(CompositePrecisionAdjustment.java:131)
	at org.sosy_lab.cpachecker.cpa.composite.CompositePrecisionAdjustment.prec(CompositePrecisionAdjustment.java:98)
	at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:88)
	at org.sosy_lab.cpachecker.cpa.arg.ARGPrecisionAdjustment.prec(ARGPrecisionAdjustment.java:58)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.handleState(CPAAlgorithm.java:356)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run0(CPAAlgorithm.java:289)
	at org.sosy_lab.cpachecker.core.algorithm.CPAAlgorithm.run(CPAAlgorithm.java:260)
	at org.sosy_lab.cpachecker.core.algorithm.CEGARAlgorithm.run(CEGARAlgorithm.java:241)
	at org.sosy_lab.cpachecker.core.CPAchecker.runAlgorithm(CPAchecker.java:510)
	at org.sosy_lab.cpachecker.core.CPAchecker.run(CPAchecker.java:375)
	at org.sosy_lab.cpachecker.cmdline.CPAMain.main(CPAMain.java:169)
```
From the surrounding log, the exception message, and the stack trace we can assume that this happens if a shutdown is triggered during a call to `push()`. JavaSMT needs to handle this properly and throw an `InterruptedException` instead of an unchecked exception.

**Comment by kfriedberger** [comment] 2023-01-16 20:45
Thanks for the report. The issue is fixed and will be part of the next release.

**Comment by PhilippWendler** [comment] 2023-06-12 08:04
Fix is incomplete, still [seeing this with JavaSMT 4.0](https://buildbot.sosy-lab.org/cpachecker/results/policyIteration/01047.-r_integration-policyIteration.2023-06-12_09-40-14.results.html#/table?filter=0(0*status*(status(in(TIMEOUT%20%28EXCEPTION%29))))).

**Closed** 2023-06-12 18:59 UTC
Labels: enhancement, Z3

**Comment by PhilippWendler** [comment] 2026-04-24 14:11
This issue now exists again, but because the circumstances are different, I have created a new issue here: #654
