### ISSUE TITLE
Yices2 dependencies using maven

### ISSUE THREAD

**Issue by hernanponcedeleon** [sosy-lab/java-smt#243] opened 2021-08-07 13:53 UTC
I'm using `maven` to build my project and I cannot find how to add the dependencies for `yices2` to my `pom` file. [This](https://github.com/sosy-lab/java-smt/blob/master/doc/Example-Maven-Project/pom.xml) example shows how to add all solver dependencies except `yices2`.

I couldn't either find the corresponding jar in [this](https://repo.maven.apache.org/maven2/org/sosy-lab/) maven repository and there is no `pom` file for `yices2` in `solvers_maven_conf`.

Is `yices2` yet not supported when building using `maven`?

**Comment by kfriedberger** [comment] 2021-08-07 21:27
As Yices2 is under GPL, releasing it is complex. Yices2 is not yet supported via Maven.
This is a duplicate of #221.

**Closed by kfriedberger** 2021-08-07 21:27 UTC
