### ISSUE TITLE
Not able to run in war

### ISSUE THREAD

**Issue by uncttao** [sosy-lab/java-smt#205] opened 2020-09-08 01:33 UTC
When invoking java-smt in a war-packaged application, it raises the following exception. It seems to be caused by the assumptions made by java-smt at runtime about the file systems where paths are expected to resolve.

```
java.nio.file.FileSystemNotFoundException: null
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
        at java.nio.file.Paths.get(Paths.java:143)
        at org.sosy_lab.common.NativeLibraries.getPathToJar(NativeLibraries.java:201)
        at org.sosy_lab.common.NativeLibraries.getNativeLibraryPath(NativeLibraries.java:188)
        at org.sosy_lab.common.NativeLibraries.findPathForLibrary(NativeLibraries.java:236)
        at org.sosy_lab.common.ExtendedURLClassLoader.findLibrary(ExtendedURLClassLoader.java:100)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1823)
        at java.lang.Runtime.loadLibrary0(Runtime.java:871)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.sosy_lab.java_smt.solvers.z3.Z3SolverContext.create(Z3SolverContext.java:141)
        at org.sosy_lab.java_smt.solvers.z3.Z3LoadingFactory.generateSolverContext(Z3LoadingFactory.java:53)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext0(SolverContextFactory.java:217)
        at org.sosy_lab.java_smt.SolverContextFactory.generateContext(SolverContextFactory.java:170)
        at org.sosy_lab.java_smt.SolverContextFactory.createSolverContext(SolverContextFactory.java:260)
        ......
```

Version: 3.3.0

**Comment by kfriedberger** [comment] 2020-09-08 06:31
Thanks for your bug report. We will take a look.

**Comment by kfriedberger** [comment] 2020-09-12 14:07
Hi @uncttao ,
I have never packages JavaSMT into a WAR file.
Could you provide more details about your webapp?
How did you install JavaSMT? How did you install the dependencies (especially the library for Z3)?
How did you package it into a WAR file? Is Z3 included in the WAR file?
Best,
Karlheinz

**Comment by kfriedberger** [comment] 2020-09-12 14:22
Additionally, JavaSMT 3.3.0 is already outdated and can be replaced with JavaSMT 3.5.0 or 3.6.0,
where a newer version of `org.sosy-lab.common` is used. Could you try with the new version?

**Comment by uncttao** [comment] 2020-09-14 02:18
We tried the newest version. It has the exact same problem.

With regard to the WAR, we packaged it using the `spring-boot` package routine under Maven. `java-smt` was imported as a dependency through Maven. We manually included all necessary native files, but the above error is thrown.

**Comment by baierd** [comment] 2020-12-14 20:38
@uncttao could you provide us with the pom.xml you used?
Do you package the native library into the WAR file?
What system are you using?
I am currently working on Maven support and would like to resolve this if possible.

**Comment by uncttao** [comment] 2020-12-15 22:18
> @uncttao could you provide us with the pom.xml you used?
> Do you package the native library into the WAR file?
> What system are you using?
> I am currently working on Maven support and would like to resolve this if possible.

@baierd Hi, thanks so much for your support. Unfortunately, I no longer work in the corporation, nor do I have access to the files any longer. You could try initializing a vanilla spring boot project and add the java-smt library as a simple Maven dependency. Then, use the spring boot packaging mechanism to package the entire app. You should run into the same issue.

**Comment by baierd** [comment] 2020-12-15 22:28
Thanks, i will try this!

**Comment by baierd** [comment] 2020-12-31 03:36
Adding the solver(s) at the wrong position caused this (due to our commons lib). Either Maven does not know that there are external dependencys and/or where to put them, so when trying to load them it fails because they are not in the WAR. 
Or you packaged them into the WAR file but at the wrong position (they need to be relative to the commons lib, i.e. in the same folder, and not JavaSMT).

Anyway this shouldn't be a problem in the future as we will provide Z3 via Maven + a how to use shortly, which should solve this.
@kfriedberger you can either connect this to #201 or close it.

**Comment by kfriedberger** [comment] 2020-12-31 08:11
Lets wait for #201. Then we can close it.

**Comment by kfriedberger** [comment] 2021-01-27 11:27
Our Maven example project allows to build a functional self-contained war file.
I can not reproduce this exception and close this issue.

**Closed by kfriedberger** 2021-01-27 11:27 UTC
