### ISSUE TITLE
Refactor newProverEnvironment methods

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/java-smt#18] opened 2015-12-17 11:18 UTC
Methods with boolean parameters are bad, because the semantic of the parameter is not clear when looking at a call site, and because they can be easily confused.

The methods only exist in their current form because they were meant to be implemented, not called (for implementors the boolean parameters are convenient).

Thus these methods should be refactored (AbstractFormulaManager could convert the new variant to the existing methods).
Two possibilities exist:
- like in CPAchecker with a separate method per combination of parameters
- with an enum that selects which features are enabled (like in `java.nio.file.Files.newOutputStream()`)

**Comment by cheshire** [comment] 2015-12-18 12:59
The methods should also provide logging wrapping (I imagine `Solver` in CPAchecker should just use that wrapping)

**Comment by kfriedberger** [comment] 2015-12-23 13:54
Do we need the flag `shared` in the method `newProverEnvironmentWithInterpolation`?
Only Mathsat uses it and there is also a default flag (always `true`) used for the non-interpolating Mathsat-prover. In CPAchecker this flag is always seet to `false`. Does someone know the reason for this? I would suggest to remove this flag and use `true` for all Mathsat-provers.

**Comment by cheshire** [comment] 2015-12-23 13:57
When I was using Mathsat, it only worked with shared=true. I would always set it to true, and then the user should use a separate FormulaManager if they want another contxt.

**Comment by PhilippWendler** [comment] 2015-12-23 14:02
> Do we need the flag shared in the method newProverEnvironmentWithInterpolation?

Probably not. Sharing can be beneficial or not depending on the circumstances, but we never really managed to experiment with this properly.

MathSAT should however work find with shared=false. Note that this is still separate than using a separate FormulaManager, because with a separate FormulaManager user will have to copy formulas using strings, whereas MathSAT allows internal copying of formulas (more efficient). If we want to support this, we could have a `FormulaManager.copyTo(Formula, FormulaManager)` method that special-cases when both environments are of the same solver.

**Comment by cheshire** [comment] 2016-01-06 16:44
> like in CPAchecker with a separate method per combination of parameters

But it's even worse in CPAchecker.
I can get a prover environment with either unsat core generation, or model generation, but not both.
I also have to guess that the default prover environment has neither models nor unsat cores (i can understand latter, but not the former).

The problem is that Java doesn't have default methods which are sometimes really necessary. Nothing we can do about that.
I wouldn't feel right about writing up 4 methods with very long, almost same names (all combinations of generate models + generate unsat cores).
Thus I'm tempted to close it, because I think even booleans are better than the "cleaner" interface CPAchecker exposes.

If we *really* want it, we can:

 - Defer prover environment initialization until something is done to it.
 - Expose builder-like API:

```java
with (ProverEnvironment env = mgr.getProverEnvironment().withModels().withUnsatCore()) {
    // ....
}
```

**Comment by PhilippWendler** [comment] 2016-01-07 05:24
I think the booleans are worse, because they are the most error-prone variant, and as soon as we add new features we need to keep the old methods for backwards compatibility such that we end up with more and more getProverEnvironment overloads with varying numbers of boolean parameters.

Either the builder or the enum solution proposed in my initial post should be done.

**Comment by cheshire** [comment] 2016-01-07 10:31
Oh right, I haven't noticed the post suggesting an enum. OK let's do an enum.

**Closed** 2016-01-11 12:29 UTC
